
name: Upload build to Firebase workflow

on:
  repository_dispatch:
    types: [upload-build]

jobs:          
  upload-build:
    name: Upload build to Firebase
    runs-on: macos-latest
    env:
      FIREBASE_SECRET_KEY: ${{ secrets.FIREBASE_SECRET_KEY }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Setup Python and dependencies
        uses: actions/setup-python@v3
        with:
            python-version: '3.x'
            architecture: 'x64'

      - name: Install pip dependencies
        run: |
          pip install firebase-admin
        
      - name: Get secret key
        id: write_key_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'firebase_secret_key.json' # name of the written key file
          fileDir: './secrets/'
          encodedString: '${{ secrets.FIREBASE_SECRET_KEY }}' # Secret stored in Github secrets

      - name: Download latest build
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: app-release-${{ github.event.client_payload.version }}
          workflow: build_apk.yml
          github_token: ${{ github.event.client_payload.token }}
      
      - name: Upload file to firebase
        run: |
          export FILE_NAME=app-release-${{ github.event.client_payload.version }}-signed
          mkdir -p build/app/outputs/flutter-apk/
          mv ./${FILE_NAME}.apk build/app/outputs/flutter-apk/${FILE_NAME}.apk
          python ./.github/scripts/upload_script.py

  create-release-notes:
    name: Create release notes for the version
    runs-on: ubuntu-latest
    needs: [upload-build]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Create Release Notes
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.event.client_payload.token }}
      with:
        tag_name: ${{ github.event.client_payload.version }}
        release_name: Release ${{ github.event.client_payload.version }}
        draft: false
        prerelease: false
